name: beauty
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_links: ^6.4.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  camerawesome: ^2.1.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.2
  dio_cache_interceptor: ^3.5.1
  file_picker: ^10.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^18.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_timezone: ^4.1.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.3
  google_maps_flutter: ^2.12.3
  google_polyline_algorithm: ^3.1.0
  google_sign_in: ^6.2.2
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  json_annotation: ^4.9.0
  nested_scroll_view_plus: ^3.0.0
  open_settings: ^2.0.2
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  photo_manager: ^3.6.4
  photo_manager_image_provider: ^2.2.0
  photo_view: ^0.15.0
  potatoes: ^3.0.8+1
  potatoes_secured_preferences: ^1.0.2
  readmore: ^3.0.0
  share_plus: ^10.1.4
  sign_in_with_apple: ^6.1.4
  store_redirect: ^2.0.4
  stories_page_view: ^0.0.5
  url_launcher: ^6.3.1
  table_calendar: ^3.1.3
  time_change_detector: ^0.0.4
  video_player: ^2.9.5

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  freezed: ^2.5.8
  json_serializable: ^6.9.4

  flutter_lints: ^5.0.0
  crypto: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/images/

  fonts:
    - family: ARCO
      fonts:
        - asset: assets/fonts/ARCO.ttf
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-VariableFont_wght.ttf
          style: normal
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
