// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9aK55Vt7RQOBZ2fbKwpcUmbeXPY3ilHM',
    appId: '1:167934514170:web:a5f5c14620c45cf80b4a43',
    messagingSenderId: '167934514170',
    projectId: 'signyale',
    authDomain: 'signyale.firebaseapp.com',
    storageBucket: 'signyale.firebasestorage.app',
    measurementId: 'G-VS1G66E5RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_MO4NzZ9Xqjmt-G2EwNx8RI8ei7VVws',
    appId: '1:69380599834:android:46f8cd000e35273092a1a3',
    messagingSenderId: '69380599834',
    projectId: 'beauty-online-f51ac',
    storageBucket: 'beauty-online-f51ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8bcbju81cfhervS33FUqYx-7DozpbuAY',
    appId: '1:69380599834:ios:9ca182c9dfeae34492a1a3',
    messagingSenderId: '69380599834',
    projectId: 'beauty-online-f51ac',
    storageBucket: 'beauty-online-f51ac.firebasestorage.app',
    iosClientId: '69380599834-rhvcgbg0kr6shpum7pm6ierquf9o44to.apps.googleusercontent.com',
    iosBundleId: 'com.beauty.online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpUJLKRuXgks6qMU-D8o3m4C6shOSAmbQ',
    appId: '1:167934514170:ios:bffb43f0a6a0b2db0b4a43',
    messagingSenderId: '167934514170',
    projectId: 'signyale',
    storageBucket: 'signyale.firebasestorage.app',
    androidClientId: '167934514170-4p16bc0b74v3j24b8irvd9vi1d09mgps.apps.googleusercontent.com',
    iosClientId: '167934514170-1genpnurqh6n6ignssi71nhh4490pt7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.signyale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9aK55Vt7RQOBZ2fbKwpcUmbeXPY3ilHM',
    appId: '1:167934514170:web:235e7c8502f4faf90b4a43',
    messagingSenderId: '167934514170',
    projectId: 'signyale',
    authDomain: 'signyale.firebaseapp.com',
    storageBucket: 'signyale.firebasestorage.app',
    measurementId: 'G-Z9KX85BR2R',
  );

}